## Analyzing Data

In [17]:
import pandas as pd
import json

In [19]:
# Reading json data into dataframe
df = pd.read_json('DataFiles/clean_data.json')
df

,origin,destination,price,airline,flight_number,departure_at,return_at,transfers,expires_at,date,currency,city,coordinates,airline_name
0,SAT,LAX,280,NK,1044,2023-07-20T22:28:00-05:00,2023-08-01T07:15:00-07:00,0,2023-07-21 01:28:21+00:00,2023-07-20,usd,"Los Angeles, California","[33.9438, -118.4091]",Spirit Airlines
1,SAT,LAS,126,F9,2075,2023-07-21T22:11:00-05:00,2023-07-28T16:26:00-07:00,0,2023-07-21 01:28:21+00:00,2023-07-21,usd,"Las Vegas, Nevada","[36.084, -115.1537]",Frontier Airlines
2,SAT,BWI,150,NK,1739,2023-07-22T16:00:00-05:00,2023-08-05T21:19:00-04:00,0,2023-07-21 01:28:21+00:00,2023-07-22,usd,"Baltimore, Maryland","[39.1776, -76.6684]",Spirit Airlines
3,SAT,LAS,115,F9,2075,2023-07-23T22:23:00-05:00,2023-07-28T16:26:00-07:00,0,2023-07-21 01:28:21+00:00,2023-07-23,usd,"Las Vegas, Nevada","[36.084, -115.1537]",Frontier Airlines
4,SAT,LAS,170,F9,2075,2023-07-24T21:07:00-05:00,2023-07-28T09:20:00-07:00,0,2023-07-21 01:28:21+00:00,2023-07-24,usd,"Las Vegas, Nevada","[36.084, -115.1537]",Frontier Airlines
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
330,SAT,ORL,1823,UA,2496,2024-06-15T14:15:00-05:00,2024-06-20T17:10:00-04:00,1,2023-07-21 01:28:21+00:00,2024-06-15,usd,"Orlando, Florida","[28.4311, -81.3079]",United Airlines
331,SAT,HNL,668,UA,2486,2024-06-20T07:30:00-05:00,2024-06-29T07:00:00-10:00,1,2023-07-21 01:28:21+00:00,2024-06-20,usd,"Honolulu, Hawaii","[21.3186, -157.9254]",United Airlines
332,SAT,YYC,566,UA,2486,2024-06-23T07:30:00-05:00,2024-06-29T12:30:00-06:00,1,2023-07-21 01:28:21+00:00,2024-06-23,usd,"Calgary, Canada","[51.1308, -114.0131]",United Airlines
333,SAT,PHX,384,UA,2460,2024-06-30T10:00:00-05:00,2024-07-04T12:05:00-07:00,1,2023-07-21 01:28:21+00:00,2024-06-30,usd,"Phoenix, Arizona","[33.4352, -112.0101]",United Airlines
334,SAT,ATH,1690,UA,2010,2024-07-04T07:00:00-05:00,2024-07-13T11:45:00+03:00,1,2023-07-21 01:28:21+00:00,2024-07-04,usd,"Athens, Greece","[37.9358, 23.9484]",United Airlines

In [20]:
# Finding popular airlines
df['airline'].value_counts()

airline
UA    149
F9     54
NK     50
DL     24
AA     22
AM     10
B6      9
AS      6
Y4      4
VB      4
G4      1
ZZ      1
LH      1
Name: count, dtype: int64

In [11]:
# Printing every airline to write their full name
airline_array = df['airline'].unique()
for airline in airline_array:
    print(f'* {airline}:')

* NK:
* F9:
* AA:
* G4:
* UA:
* Y4:
* VB:
* B6:
* DL:
* AM:
* AS:
* ZZ:
* LH:

Airlines
* NK: Spirit Airlines
* F9: Frontier Airlines
* AA: American Airlines
* G4: Allegiant
* UA: United Airlines
* Y4: Volaris
* VB: Aeroenlace
* B6: JetBlue
* DL: Delta Airlines
* AM: Aeromexico
* AS: Alaska Airlines
* ZZ: N/A
* LH: Desutsche Lufthansa

In [14]:
# Printing every aiport to wrtie their city names
airport_array = df['destination'].unique()
for airport in airport_array:
    print(f'* {airport}: ')

* LAX:
* LAS:
* BWI:
* ABI:
* FLL:
* CHI:
* ORL:
* ATL:
* AVL:
* RDU:
* BOS:
* DTT:
* TPA:
* DEN:
* PDX:
* HNL:
* MYR:
* MEX:
* DFW:
* SAN:
* CAE:
* MTY:
* SDF:
* ONT:
* SEA:
* SFO:
* PHX:
* DUB:
* MSY:
* PHL:
* GDL:
* BNA:
* BIL:
* BZE:
* LCH:
* NYC:
* PVR:
* COS:
* PTY:
* SAL:
* SLU:
* HAV:
* MKC:
* CUN:
* SGN:
* MLB:
* GGT:
* SJU:
* SBN:
* CVN:
* QHO:
* VCE:
* FAO:
* SJD:
* FSD:
* ANC:
* BTR:
* JTR:
* REK:
* TYO:
* BKK:
* YYC:
* ATH:

Destinations
* LAX: Los Angeles, California
* LAS: Las Vegas, Nevada 
* BWI: Baltimore, Maryland
* ABI: Abilene, Texas
* FLL: Fort Lauderdale, Florida
* CHI: Chicago, Illinois
* ORL: Orlando, Florida
* ATL: Atlanta, Georgia
* AVL: Asheville, North Carolina
* RDU: Morrisville, North Carolina
* BOS: Boston, Massachusetts
* DTT: Detroit, Michigan
* TPA: Tampa, Florida
* DEN: Denver, Colorado
* PDX: Portland, Oregon
* HNL: Honolulu, Hawaii
* MYR: Myrtle Beach, South Carolina
* MEX: Mexico City, Mexico
* DFW: Dallas Fort Worth, Texas
* SAN: San Diego, California
* CAE: Columbia, South Carolina
* MTY: Monterrey, Mexico
* SDF: Louisville, Kentucky
* ONT: Ontario, California
* SEA: Seattle, Washington
* SFO: San Francisco, California
* PHX: Phoenix, Arizona
* DUB: Dublin, Ireland
* MSY: New Orleans, Louisiana
* PHL: Philadelphia, Pennsylvania
* GDL: Guadalajara, Mexico
* BNA: Nashville, Tennessee
* BIL: Billings, Montana
* BZE: Belize City, Belize
* LCH: Lake Charles, Louisiana
* NYC: New York City, New York
* PVR: Puerto Vallarta, Mexico
* COS: Colorado Springs, Colorado
* PTY: Panama City, Panama
* SAL: San Salvador, EL Salvador
* SLU: Castries, Saint Lucia
* HAV: Havana, Cuba
* MKC: Kansas City, Missouri
* CUN: Cancun, Mexico
* SGN: Tan Son Nhat, Vietnam
* MLB: Melbourne, Florida
* GGT: Exuma, The Bahamas
* SJU: Carolina, Puerto Rico
* SBN: South Bend, Indiana
* CVN: Clovis, New Mexico
* QHO: Houston, Texas
* VCE: Venice, Italy
* FAO: Faro, Portugal
* SJD: San Jose del Cabo, Mexico
* FSD: Sioux Falls, South Dakota 
* ANC: Anchorage, Alaska
* BTR: Baton Rouge, Louisiana
* JTR: Santorini, Greece
* REK: Reykjavik, Iceland
* TYO: Tokyo, Japan
* BKK: Suvarnabhumi, Thailand
* YYC: Calgary, Canada
* ATH: Athens, Greece

In [21]:
df.loc[df['city'] == 'New York City, New York']

,origin,destination,price,airline,flight_number,departure_at,return_at,transfers,expires_at,date,currency,city,coordinates,airline_name
121,SAT,NYC,299,AA,671,2023-11-18T06:29:00-06:00,2023-11-29T16:00:00-05:00,1,2023-07-21 01:28:21+00:00,2023-11-18,usd,"New York City, New York","[40.6446, -73.7797]",American Airlines
131,SAT,NYC,202,UA,1741,2023-11-28T13:06:00-06:00,2023-12-02T15:29:00-05:00,1,2023-07-21 01:28:21+00:00,2023-11-28,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
132,SAT,NYC,186,UA,1715,2023-11-29T13:25:00-06:00,2023-12-05T16:25:00-05:00,1,2023-07-21 01:28:21+00:00,2023-11-29,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
153,SAT,NYC,296,UA,1347,2023-12-20T07:30:00-06:00,2023-12-25T14:46:00-05:00,1,2023-07-21 01:28:21+00:00,2023-12-20,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
155,SAT,NYC,360,UA,1347,2023-12-22T07:30:00-06:00,2023-12-25T14:46:00-05:00,1,2023-07-21 01:28:21+00:00,2023-12-22,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
156,SAT,NYC,324,B6,1826,2023-12-23T14:42:00-06:00,2023-12-26T10:30:00-05:00,0,2023-07-21 01:28:21+00:00,2023-12-23,usd,"New York City, New York","[40.6446, -73.7797]",JetBlue
157,SAT,NYC,260,UA,2250,2023-12-24T11:45:00-06:00,2023-12-27T10:30:00-05:00,1,2023-07-21 01:28:21+00:00,2023-12-24,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
160,SAT,NYC,357,UA,1347,2023-12-27T07:30:00-06:00,2023-12-28T10:30:00-05:00,1,2023-07-21 01:28:21+00:00,2023-12-27,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
161,SAT,NYC,326,B6,1826,2023-12-28T14:42:00-06:00,2024-01-02T10:30:00-05:00,0,2023-07-21 01:28:21+00:00,2023-12-28,usd,"New York City, New York","[40.6446, -73.7797]",JetBlue
162,SAT,NYC,286,AA,1957,2023-12-29T12:41:00-06:00,2024-01-05T08:25:00-05:00,1,2023-07-21 01:28:21+00:00,2023-12-29,usd,"New York City, New York","[40.6446, -73.7797]",American Airlines
168,SAT,NYC,192,UA,2010,2024-01-04T07:00:00-06:00,2024-01-23T14:00:00-05:00,1,2023-07-21 01:28:21+00:00,2024-01-04,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
169,SAT,NYC,192,UA,2010,2024-01-05T07:00:00-06:00,2024-01-23T15:00:00-05:00,1,2023-07-21 01:28:21+00:00,2024-01-05,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
172,SAT,NYC,217,UA,2010,2024-01-08T07:00:00-06:00,2024-01-12T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-08,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
173,SAT,NYC,217,B6,1826,2024-01-09T15:51:00-06:00,2024-01-12T09:30:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-09,usd,"New York City, New York","[40.6446, -73.7797]",JetBlue
175,SAT,NYC,217,UA,2010,2024-01-11T07:00:00-06:00,2024-01-15T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-11,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
176,SAT,NYC,217,UA,2010,2024-01-12T07:00:00-06:00,2024-01-15T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-12,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
179,SAT,NYC,217,UA,2010,2024-01-15T07:00:00-06:00,2024-01-19T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-15,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
181,SAT,NYC,186,UA,1347,2024-01-17T07:30:00-06:00,2024-01-31T10:20:00-05:00,1,2023-07-21 01:28:21+00:00,2024-01-17,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
188,SAT,NYC,186,UA,2486,2024-01-24T07:30:00-06:00,2024-01-31T15:45:00-05:00,1,2023-07-21 01:28:21+00:00,2024-01-24,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
189,SAT,NYC,217,UA,2010,2024-01-25T07:00:00-06:00,2024-01-28T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-25,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
191,SAT,NYC,217,UA,2010,2024-01-27T07:00:00-06:00,2024-01-29T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-01-27,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
196,SAT,NYC,217,UA,2010,2024-02-01T07:00:00-06:00,2024-02-04T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-02-01,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
197,SAT,NYC,217,UA,2010,2024-02-02T07:00:00-06:00,2024-02-04T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-02-02,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
200,SAT,NYC,217,DL,1056,2024-02-05T13:50:00-06:00,2024-02-09T09:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-02-05,usd,"New York City, New York","[40.6446, -73.7797]",Delta Airlines
203,SAT,NYC,217,UA,2010,2024-02-08T07:00:00-06:00,2024-02-12T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-02-08,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
204,SAT,NYC,217,UA,2010,2024-02-09T07:00:00-06:00,2024-02-12T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-02-09,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
205,SAT,NYC,202,UA,2010,2024-02-10T07:00:00-06:00,2024-02-14T17:00:00-05:00,1,2023-07-21 01:28:21+00:00,2024-02-10,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
209,SAT,NYC,202,UA,1715,2024-02-14T13:42:00-06:00,2024-02-18T08:45:00-05:00,1,2023-07-21 01:28:21+00:00,2024-02-14,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
212,SAT,NYC,217,UA,2010,2024-02-17T07:00:00-06:00,2024-02-20T08:45:00-05:00,0,2023-07-21 01:28:21+00:00,2024-02-17,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
213,SAT,NYC,202,UA,2010,2024-02-18T07:00:00-06:00,2024-02-21T10:20:00-05:00,1,2023-07-21 01:28:21+00:00,2024-02-18,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
228,SAT,NYC,202,UA,1741,2024-03-04T12:50:00-06:00,2024-03-06T07:55:00-05:00,1,2023-07-21 01:28:21+00:00,2024-03-04,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
238,SAT,NYC,271,UA,1347,2024-03-14T07:30:00-05:00,2024-03-18T15:45:00-04:00,1,2023-07-21 01:28:21+00:00,2024-03-14,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
239,SAT,NYC,226,UA,1894,2024-03-15T07:00:00-05:00,2024-03-23T06:05:00-04:00,1,2023-07-21 01:28:21+00:00,2024-03-15,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
244,SAT,NYC,277,B6,1826,2024-03-20T14:40:00-05:00,2024-04-01T10:35:00-04:00,0,2023-07-21 01:28:21+00:00,2024-03-20,usd,"New York City, New York","[40.6446, -73.7797]",JetBlue
251,SAT,NYC,222,UA,2010,2024-03-27T07:00:00-05:00,2024-03-30T14:00:00-04:00,1,2023-07-21 01:28:21+00:00,2024-03-27,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
258,SAT,NYC,222,UA,2010,2024-04-03T07:00:00-05:00,2024-04-08T17:00:00-04:00,1,2023-07-21 01:28:21+00:00,2024-04-03,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
272,SAT,NYC,237,DL,1056,2024-04-17T13:50:00-05:00,2024-05-04T09:45:00-04:00,0,2023-07-21 01:28:21+00:00,2024-04-17,usd,"New York City, New York","[40.6446, -73.7797]",Delta Airlines
277,SAT,NYC,316,UA,1347,2024-04-22T07:30:00-05:00,2024-05-02T15:45:00-04:00,1,2023-07-21 01:28:21+00:00,2024-04-22,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
278,SAT,NYC,267,UA,1741,2024-04-23T12:50:00-05:00,2024-05-02T15:45:00-04:00,1,2023-07-21 01:28:21+00:00,2024-04-23,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
283,SAT,NYC,347,B6,1826,2024-04-28T14:40:00-05:00,2024-05-02T11:30:00-04:00,0,2023-07-21 01:28:21+00:00,2024-04-28,usd,"New York City, New York","[40.6446, -73.7797]",JetBlue
285,SAT,NYC,217,DL,1056,2024-04-30T13:50:00-05:00,2024-05-11T09:45:00-04:00,0,2023-07-21 01:28:21+00:00,2024-04-30,usd,"New York City, New York","[40.6446, -73.7797]",Delta Airlines
286,SAT,NYC,226,UA,1894,2024-05-01T07:00:00-05:00,2024-05-07T17:00:00-04:00,1,2023-07-21 01:28:21+00:00,2024-05-01,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
288,SAT,NYC,406,UA,2460,2024-05-03T10:00:00-05:00,2024-05-12T06:05:00-04:00,1,2023-07-21 01:28:21+00:00,2024-05-03,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
291,SAT,NYC,277,DL,1056,2024-05-06T13:50:00-05:00,2024-05-22T09:45:00-04:00,0,2023-07-21 01:28:21+00:00,2024-05-06,usd,"New York City, New York","[40.6446, -73.7797]",Delta Airlines
292,SAT,NYC,217,UA,2010,2024-05-07T07:00:00-05:00,2024-05-08T12:31:00-04:00,0,2023-07-21 01:28:21+00:00,2024-05-07,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
299,SAT,NYC,222,UA,1347,2024-05-14T07:30:00-05:00,2024-05-29T12:31:00-04:00,1,2023-07-21 01:28:21+00:00,2024-05-14,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
300,SAT,NYC,267,UA,1347,2024-05-15T07:30:00-05:00,2024-05-29T12:31:00-04:00,1,2023-07-21 01:28:21+00:00,2024-05-15,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
301,SAT,NYC,360,UA,1347,2024-05-16T07:30:00-05:00,2024-05-28T12:30:00-04:00,2,2023-07-21 01:28:21+00:00,2024-05-16,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines
305,SAT,NYC,396,DL,1465,2024-05-20T18:20:00-05:00,2024-06-03T06:00:00-04:00,1,2023-07-21 01:28:21+00:00,2024-05-20,usd,"New York City, New York","[40.6446, -73.7797]",Delta Airlines
317,SAT,NYC,317,UA,680,2024-06-01T16:45:00-05:00,2024-06-05T12:31:00-04:00,1,2023-07-21 01:28:21+00:00,2024-06-01,usd,"New York City, New York","[40.6446, -73.7797]",United Airlines